#! /usr/bin/env bash

# This script patches the documentation generated by `rustdoc`. Patching is not
# idempotent; the generated documentation should be copied into the site
# directory before patching.

set -e

bash_source_dir=$(dirname "$BASH_SOURCE")

root="${1:-$bash_source_dir}"
patch="$root/patch"
doc="$root/out/doc/rustdoc"

# Append CSS to remove drop shadows from logo images.
for theme in "ayu.css" "dark.css" "light.css"
do
    theme="$doc/$theme"
    if [ -f "$theme" ]; then
        cat "$patch/logo-container.css" >> "$theme"
    fi
done
